// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repository;

namespace Repository.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20200331171548_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Entities.Models.City", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long>("StateID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.HasIndex("StateID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 1",
                            StateID = 1L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 2",
                            StateID = 1L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 3",
                            StateID = 2L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 4",
                            StateID = 2L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 5",
                            StateID = 3L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 6",
                            StateID = 3L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 7",
                            StateID = 4L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 8",
                            StateID = 4L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 9",
                            StateID = 5L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 10",
                            StateID = 5L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("CityID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("StreetName")
                        .HasColumnType("text");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.HasIndex("CityID");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            CityID = 1L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 1",
                            StreetName = "Street Name",
                            StreetNumber = 667,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2L,
                            CityID = 2L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 2",
                            StreetName = "Street Name",
                            StreetNumber = 3659,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3L,
                            CityID = 3L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 3",
                            StreetName = "Street Name",
                            StreetNumber = 1675,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4L,
                            CityID = 4L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 4",
                            StreetName = "Street Name",
                            StreetNumber = 4454,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5L,
                            CityID = 5L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 5",
                            StreetName = "Street Name",
                            StreetNumber = 40,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6L,
                            CityID = 6L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 6",
                            StreetName = "Street Name",
                            StreetNumber = 1235,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7L,
                            CityID = 7L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 7",
                            StreetName = "Street Name",
                            StreetNumber = 687,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8L,
                            CityID = 8L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 8",
                            StreetName = "Street Name",
                            StreetNumber = 2850,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9L,
                            CityID = 9L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 9",
                            StreetName = "Street Name",
                            StreetNumber = 1554,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10L,
                            CityID = 10L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 10",
                            StreetName = "Street Name",
                            StreetNumber = 4053,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Models.Contact", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("CityID")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text");

                    b.Property<string>("StreetName")
                        .HasColumnType("text");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.HasIndex("CityID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            BirthDate = new DateTime(1973, 10, 19, 14, 15, 47, 494, DateTimeKind.Local).AddTicks(6126),
                            CityID = 1L,
                            CompanyID = 1L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail1@mail.com",
                            Name = "Contact 1",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 4725,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2L,
                            BirthDate = new DateTime(1976, 9, 11, 14, 15, 47, 495, DateTimeKind.Local).AddTicks(629),
                            CityID = 1L,
                            CompanyID = 1L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail2@mail.com",
                            Name = "Contact 2",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 2387,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3L,
                            BirthDate = new DateTime(2000, 3, 31, 14, 15, 47, 495, DateTimeKind.Local).AddTicks(828),
                            CityID = 2L,
                            CompanyID = 2L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail3@mail.com",
                            Name = "Contact 3",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 3345,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4L,
                            BirthDate = new DateTime(1938, 6, 20, 14, 15, 47, 495, DateTimeKind.Local).AddTicks(902),
                            CityID = 2L,
                            CompanyID = 2L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail4@mail.com",
                            Name = "Contact 4",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 864,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5L,
                            BirthDate = new DateTime(1971, 12, 20, 14, 15, 47, 495, DateTimeKind.Local).AddTicks(971),
                            CityID = 3L,
                            CompanyID = 3L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail5@mail.com",
                            Name = "Contact 5",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 1458,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6L,
                            BirthDate = new DateTime(1960, 1, 13, 14, 15, 47, 495, DateTimeKind.Local).AddTicks(1049),
                            CityID = 3L,
                            CompanyID = 3L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail6@mail.com",
                            Name = "Contact 6",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 3896,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7L,
                            BirthDate = new DateTime(1994, 4, 16, 14, 15, 47, 495, DateTimeKind.Local).AddTicks(1118),
                            CityID = 4L,
                            CompanyID = 4L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail7@mail.com",
                            Name = "Contact 7",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 1254,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8L,
                            BirthDate = new DateTime(1983, 9, 26, 14, 15, 47, 495, DateTimeKind.Local).AddTicks(1181),
                            CityID = 4L,
                            CompanyID = 4L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail8@mail.com",
                            Name = "Contact 8",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 71,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9L,
                            BirthDate = new DateTime(1934, 8, 23, 14, 15, 47, 495, DateTimeKind.Local).AddTicks(1249),
                            CityID = 5L,
                            CompanyID = 5L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail9@mail.com",
                            Name = "Contact 9",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 576,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10L,
                            BirthDate = new DateTime(1930, 3, 18, 14, 15, 47, 495, DateTimeKind.Local).AddTicks(1317),
                            CityID = 5L,
                            CompanyID = 5L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail10@mail.com",
                            Name = "Contact 10",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 4335,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 11L,
                            BirthDate = new DateTime(1965, 8, 21, 14, 15, 47, 495, DateTimeKind.Local).AddTicks(1385),
                            CityID = 6L,
                            CompanyID = 6L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail11@mail.com",
                            Name = "Contact 11",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 1273,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 12L,
                            BirthDate = new DateTime(1945, 11, 17, 14, 15, 47, 495, DateTimeKind.Local).AddTicks(1468),
                            CityID = 6L,
                            CompanyID = 6L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail12@mail.com",
                            Name = "Contact 12",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 3199,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 13L,
                            BirthDate = new DateTime(1970, 8, 27, 14, 15, 47, 495, DateTimeKind.Local).AddTicks(1626),
                            CityID = 7L,
                            CompanyID = 7L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail13@mail.com",
                            Name = "Contact 13",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 534,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 14L,
                            BirthDate = new DateTime(1971, 1, 2, 14, 15, 47, 495, DateTimeKind.Local).AddTicks(1718),
                            CityID = 7L,
                            CompanyID = 7L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail14@mail.com",
                            Name = "Contact 14",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 4553,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 15L,
                            BirthDate = new DateTime(1963, 10, 2, 14, 15, 47, 495, DateTimeKind.Local).AddTicks(1774),
                            CityID = 8L,
                            CompanyID = 8L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail15@mail.com",
                            Name = "Contact 15",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 284,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 16L,
                            BirthDate = new DateTime(1969, 4, 22, 14, 15, 47, 495, DateTimeKind.Local).AddTicks(1856),
                            CityID = 8L,
                            CompanyID = 8L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail16@mail.com",
                            Name = "Contact 16",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 4199,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 17L,
                            BirthDate = new DateTime(1991, 2, 9, 14, 15, 47, 495, DateTimeKind.Local).AddTicks(1916),
                            CityID = 9L,
                            CompanyID = 9L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail17@mail.com",
                            Name = "Contact 17",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 2086,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 18L,
                            BirthDate = new DateTime(2000, 9, 18, 14, 15, 47, 495, DateTimeKind.Local).AddTicks(1986),
                            CityID = 9L,
                            CompanyID = 9L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail18@mail.com",
                            Name = "Contact 18",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 4803,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 19L,
                            BirthDate = new DateTime(1928, 1, 6, 14, 15, 47, 495, DateTimeKind.Local).AddTicks(2051),
                            CityID = 10L,
                            CompanyID = 10L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail19@mail.com",
                            Name = "Contact 19",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 709,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 20L,
                            BirthDate = new DateTime(1981, 8, 6, 14, 15, 47, 495, DateTimeKind.Local).AddTicks(2117),
                            CityID = 10L,
                            CompanyID = 10L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail20@mail.com",
                            Name = "Contact 20",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 1261,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Models.Phone", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("ContactID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<long>("PhoneTypeID")
                        .HasColumnType("bigint");

                    b.Property<string>("Prefix")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.HasIndex("ContactID");

                    b.HasIndex("PhoneTypeID");

                    b.ToTable("Phones");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            ContactID = 1L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "13082308",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2L,
                            ContactID = 2L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "45006772",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3L,
                            ContactID = 3L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "87915621",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4L,
                            ContactID = 4L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "21918660",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5L,
                            ContactID = 5L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "43800520",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6L,
                            ContactID = 6L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "68697270",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7L,
                            ContactID = 7L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "53883108",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8L,
                            ContactID = 8L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "29505464",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9L,
                            ContactID = 9L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "89049982",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10L,
                            ContactID = 10L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "79525416",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 11L,
                            ContactID = 11L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "22838497",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 12L,
                            ContactID = 12L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "45487436",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 13L,
                            ContactID = 13L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "73596150",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 14L,
                            ContactID = 14L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "56806799",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 15L,
                            ContactID = 15L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "60544866",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 16L,
                            ContactID = 16L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "57155732",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 17L,
                            ContactID = 17L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "73517982",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 18L,
                            ContactID = 18L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "86143261",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 19L,
                            ContactID = 19L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "29327710",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 20L,
                            ContactID = 20L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "37268810",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 21L,
                            ContactID = 1L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "24914982",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 22L,
                            ContactID = 2L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "82379261",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 23L,
                            ContactID = 3L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "69237232",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 24L,
                            ContactID = 4L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "86203476",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 25L,
                            ContactID = 5L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "57437936",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 26L,
                            ContactID = 6L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "45813684",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 27L,
                            ContactID = 7L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "17181636",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 28L,
                            ContactID = 8L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "19066743",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 29L,
                            ContactID = 9L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "25984454",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 30L,
                            ContactID = 10L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "95826519",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 31L,
                            ContactID = 11L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "19678837",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 32L,
                            ContactID = 12L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "37371293",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 33L,
                            ContactID = 13L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "55408796",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 34L,
                            ContactID = 14L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "65031818",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 35L,
                            ContactID = 15L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "79963571",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 36L,
                            ContactID = 16L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "88737029",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 37L,
                            ContactID = 17L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "61155058",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 38L,
                            ContactID = 18L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "57174704",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 39L,
                            ContactID = 19L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "34710001",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 40L,
                            ContactID = 20L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "51898963",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Models.PhoneType", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.ToTable("PhoneTypes");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "work",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "personal",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Models.State", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "State 1",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "State 2",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "State 3",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "State 4",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5L,
                            CreatedAt = new DateTime(2020, 3, 31, 14, 15, 47, 487, DateTimeKind.Local).AddTicks(9526),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "State 5",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Models.City", b =>
                {
                    b.HasOne("Entities.Models.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.HasOne("Entities.Models.City", "City")
                        .WithMany("Companies")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Contact", b =>
                {
                    b.HasOne("Entities.Models.City", "City")
                        .WithMany("Contacts")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Phone", b =>
                {
                    b.HasOne("Entities.Models.Contact", "Contact")
                        .WithMany("Phones")
                        .HasForeignKey("ContactID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.PhoneType", "PhoneType")
                        .WithMany("Phones")
                        .HasForeignKey("PhoneTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
