// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repository;

namespace Repository.Migrations
{
    [DbContext(typeof(ContactContext))]
    partial class ContactContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Entities.Models.City", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'11', '1', '', '', 'False', '1'")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long>("StateID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.HasIndex("StateID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            Active = true,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 1",
                            StateID = 1L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2L,
                            Active = true,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 2",
                            StateID = 1L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3L,
                            Active = true,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 3",
                            StateID = 2L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4L,
                            Active = true,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 4",
                            StateID = 2L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5L,
                            Active = true,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 5",
                            StateID = 3L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6L,
                            Active = true,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 6",
                            StateID = 3L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7L,
                            Active = true,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 7",
                            StateID = 4L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8L,
                            Active = true,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 8",
                            StateID = 4L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9L,
                            Active = true,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 9",
                            StateID = 5L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10L,
                            Active = true,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 10",
                            StateID = 5L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'11', '1', '', '', 'False', '1'")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<long>("CityID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("StreetName")
                        .HasColumnType("text");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.HasIndex("CityID");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            Active = true,
                            CityID = 1L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 1",
                            StreetName = "Street Name",
                            StreetNumber = 634,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2L,
                            Active = true,
                            CityID = 2L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 2",
                            StreetName = "Street Name",
                            StreetNumber = 1202,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3L,
                            Active = true,
                            CityID = 3L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 3",
                            StreetName = "Street Name",
                            StreetNumber = 1501,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4L,
                            Active = true,
                            CityID = 4L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 4",
                            StreetName = "Street Name",
                            StreetNumber = 1968,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5L,
                            Active = true,
                            CityID = 5L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 5",
                            StreetName = "Street Name",
                            StreetNumber = 855,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6L,
                            Active = true,
                            CityID = 6L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 6",
                            StreetName = "Street Name",
                            StreetNumber = 4355,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7L,
                            Active = true,
                            CityID = 7L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 7",
                            StreetName = "Street Name",
                            StreetNumber = 147,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8L,
                            Active = true,
                            CityID = 8L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 8",
                            StreetName = "Street Name",
                            StreetNumber = 4,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9L,
                            Active = true,
                            CityID = 9L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 9",
                            StreetName = "Street Name",
                            StreetNumber = 3410,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10L,
                            Active = true,
                            CityID = 10L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 10",
                            StreetName = "Street Name",
                            StreetNumber = 4998,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Models.Contact", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'21', '1', '', '', 'False', '1'")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("CityID")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text");

                    b.Property<string>("StreetName")
                        .HasColumnType("text");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.HasIndex("CityID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            Active = false,
                            BirthDate = new DateTime(1995, 2, 24, 17, 46, 0, 826, DateTimeKind.Local).AddTicks(7971),
                            CityID = 1L,
                            CompanyID = 1L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail1@mail.com",
                            Name = "Contact 1",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 740,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2L,
                            Active = false,
                            BirthDate = new DateTime(1971, 7, 24, 17, 46, 0, 827, DateTimeKind.Local).AddTicks(2695),
                            CityID = 1L,
                            CompanyID = 1L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail2@mail.com",
                            Name = "Contact 2",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 4623,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3L,
                            Active = false,
                            BirthDate = new DateTime(1913, 12, 14, 17, 46, 0, 827, DateTimeKind.Local).AddTicks(2904),
                            CityID = 2L,
                            CompanyID = 2L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail3@mail.com",
                            Name = "Contact 3",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 3729,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4L,
                            Active = false,
                            BirthDate = new DateTime(1957, 9, 29, 17, 46, 0, 827, DateTimeKind.Local).AddTicks(2961),
                            CityID = 2L,
                            CompanyID = 2L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail4@mail.com",
                            Name = "Contact 4",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 1464,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5L,
                            Active = false,
                            BirthDate = new DateTime(1948, 7, 21, 17, 46, 0, 827, DateTimeKind.Local).AddTicks(3009),
                            CityID = 3L,
                            CompanyID = 3L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail5@mail.com",
                            Name = "Contact 5",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 670,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6L,
                            Active = false,
                            BirthDate = new DateTime(1944, 7, 27, 17, 46, 0, 827, DateTimeKind.Local).AddTicks(3063),
                            CityID = 3L,
                            CompanyID = 3L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail6@mail.com",
                            Name = "Contact 6",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 4949,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7L,
                            Active = false,
                            BirthDate = new DateTime(1947, 3, 3, 17, 46, 0, 827, DateTimeKind.Local).AddTicks(3111),
                            CityID = 4L,
                            CompanyID = 4L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail7@mail.com",
                            Name = "Contact 7",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 4115,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8L,
                            Active = false,
                            BirthDate = new DateTime(1977, 6, 20, 17, 46, 0, 827, DateTimeKind.Local).AddTicks(3177),
                            CityID = 4L,
                            CompanyID = 4L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail8@mail.com",
                            Name = "Contact 8",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 1011,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9L,
                            Active = false,
                            BirthDate = new DateTime(1917, 6, 27, 17, 46, 0, 827, DateTimeKind.Local).AddTicks(3225),
                            CityID = 5L,
                            CompanyID = 5L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail9@mail.com",
                            Name = "Contact 9",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 1212,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10L,
                            Active = false,
                            BirthDate = new DateTime(1976, 7, 15, 17, 46, 0, 827, DateTimeKind.Local).AddTicks(3273),
                            CityID = 5L,
                            CompanyID = 5L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail10@mail.com",
                            Name = "Contact 10",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 392,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 11L,
                            Active = false,
                            BirthDate = new DateTime(1911, 11, 8, 17, 46, 0, 827, DateTimeKind.Local).AddTicks(3316),
                            CityID = 6L,
                            CompanyID = 6L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail11@mail.com",
                            Name = "Contact 11",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 2274,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 12L,
                            Active = false,
                            BirthDate = new DateTime(1940, 7, 1, 17, 46, 0, 827, DateTimeKind.Local).AddTicks(3357),
                            CityID = 6L,
                            CompanyID = 6L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail12@mail.com",
                            Name = "Contact 12",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 2231,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 13L,
                            Active = false,
                            BirthDate = new DateTime(1952, 7, 6, 17, 46, 0, 827, DateTimeKind.Local).AddTicks(3399),
                            CityID = 7L,
                            CompanyID = 7L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail13@mail.com",
                            Name = "Contact 13",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 737,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 14L,
                            Active = false,
                            BirthDate = new DateTime(1958, 11, 5, 17, 46, 0, 827, DateTimeKind.Local).AddTicks(3441),
                            CityID = 7L,
                            CompanyID = 7L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail14@mail.com",
                            Name = "Contact 14",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 1692,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 15L,
                            Active = false,
                            BirthDate = new DateTime(1995, 9, 18, 17, 46, 0, 827, DateTimeKind.Local).AddTicks(3482),
                            CityID = 8L,
                            CompanyID = 8L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail15@mail.com",
                            Name = "Contact 15",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 4572,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 16L,
                            Active = false,
                            BirthDate = new DateTime(1987, 3, 9, 17, 46, 0, 827, DateTimeKind.Local).AddTicks(3525),
                            CityID = 8L,
                            CompanyID = 8L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail16@mail.com",
                            Name = "Contact 16",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 4380,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 17L,
                            Active = false,
                            BirthDate = new DateTime(1917, 2, 6, 17, 46, 0, 827, DateTimeKind.Local).AddTicks(3566),
                            CityID = 9L,
                            CompanyID = 9L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail17@mail.com",
                            Name = "Contact 17",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 3624,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 18L,
                            Active = false,
                            BirthDate = new DateTime(1985, 2, 19, 17, 46, 0, 827, DateTimeKind.Local).AddTicks(3609),
                            CityID = 9L,
                            CompanyID = 9L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail18@mail.com",
                            Name = "Contact 18",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 3900,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 19L,
                            Active = false,
                            BirthDate = new DateTime(2004, 2, 2, 17, 46, 0, 827, DateTimeKind.Local).AddTicks(3656),
                            CityID = 10L,
                            CompanyID = 10L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail19@mail.com",
                            Name = "Contact 19",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 3863,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 20L,
                            Active = false,
                            BirthDate = new DateTime(2002, 3, 30, 17, 46, 0, 827, DateTimeKind.Local).AddTicks(3698),
                            CityID = 10L,
                            CompanyID = 10L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail20@mail.com",
                            Name = "Contact 20",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 2161,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Models.Phone", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'41', '1', '', '', 'False', '1'")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<long>("ContactID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<long>("PhoneTypeID")
                        .HasColumnType("bigint");

                    b.Property<string>("Prefix")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.HasIndex("ContactID");

                    b.HasIndex("PhoneTypeID");

                    b.ToTable("Phones");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            Active = true,
                            ContactID = 1L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "80780086",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2L,
                            Active = true,
                            ContactID = 2L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "19243518",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3L,
                            Active = true,
                            ContactID = 3L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "87493964",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4L,
                            Active = true,
                            ContactID = 4L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "91818087",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5L,
                            Active = true,
                            ContactID = 5L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "25007644",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6L,
                            Active = true,
                            ContactID = 6L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "53756815",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7L,
                            Active = true,
                            ContactID = 7L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "48203061",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8L,
                            Active = true,
                            ContactID = 8L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "71592285",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9L,
                            Active = true,
                            ContactID = 9L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "28124488",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10L,
                            Active = true,
                            ContactID = 10L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "88212963",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 11L,
                            Active = true,
                            ContactID = 11L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "67004468",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 12L,
                            Active = true,
                            ContactID = 12L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "19989928",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 13L,
                            Active = true,
                            ContactID = 13L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "93093592",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 14L,
                            Active = true,
                            ContactID = 14L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "43881031",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 15L,
                            Active = true,
                            ContactID = 15L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "59544842",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 16L,
                            Active = true,
                            ContactID = 16L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "25297858",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 17L,
                            Active = true,
                            ContactID = 17L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "70920751",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 18L,
                            Active = true,
                            ContactID = 18L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "32032322",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 19L,
                            Active = true,
                            ContactID = 19L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "30488697",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 20L,
                            Active = true,
                            ContactID = 20L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "27271806",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 21L,
                            Active = true,
                            ContactID = 1L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "66943274",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 22L,
                            Active = true,
                            ContactID = 2L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "81764730",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 23L,
                            Active = true,
                            ContactID = 3L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "63986100",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 24L,
                            Active = true,
                            ContactID = 4L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "12960444",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 25L,
                            Active = true,
                            ContactID = 5L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "75940413",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 26L,
                            Active = true,
                            ContactID = 6L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "81128033",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 27L,
                            Active = true,
                            ContactID = 7L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "93068847",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 28L,
                            Active = true,
                            ContactID = 8L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "90179787",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 29L,
                            Active = true,
                            ContactID = 9L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "85756115",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 30L,
                            Active = true,
                            ContactID = 10L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "98104239",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 31L,
                            Active = true,
                            ContactID = 11L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "58309453",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 32L,
                            Active = true,
                            ContactID = 12L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "30359321",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 33L,
                            Active = true,
                            ContactID = 13L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "55326444",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 34L,
                            Active = true,
                            ContactID = 14L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "14076770",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 35L,
                            Active = true,
                            ContactID = 15L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "58178676",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 36L,
                            Active = true,
                            ContactID = 16L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "43407572",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 37L,
                            Active = true,
                            ContactID = 17L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "22579408",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 38L,
                            Active = true,
                            ContactID = 18L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "58955993",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 39L,
                            Active = true,
                            ContactID = 19L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "58493032",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 40L,
                            Active = true,
                            ContactID = 20L,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "70442163",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Models.PhoneType", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'3', '1', '', '', 'False', '1'")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.ToTable("PhoneTypes");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            Active = true,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "work",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2L,
                            Active = true,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "personal",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Models.State", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:IdentitySequenceOptions", "'6', '1', '', '', 'False', '1'")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            Active = true,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "State 1",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2L,
                            Active = true,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "State 2",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3L,
                            Active = true,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "State 3",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4L,
                            Active = true,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "State 4",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5L,
                            Active = true,
                            CreatedAt = new DateTime(2020, 3, 31, 17, 46, 0, 817, DateTimeKind.Local).AddTicks(2924),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "State 5",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Models.City", b =>
                {
                    b.HasOne("Entities.Models.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.HasOne("Entities.Models.City", "City")
                        .WithMany("Companies")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Contact", b =>
                {
                    b.HasOne("Entities.Models.City", "City")
                        .WithMany("Contacts")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Phone", b =>
                {
                    b.HasOne("Entities.Models.Contact", "Contact")
                        .WithMany("Phones")
                        .HasForeignKey("ContactID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.PhoneType", "PhoneType")
                        .WithMany("Phones")
                        .HasForeignKey("PhoneTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
