// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repository;

namespace Repository.Migrations
{
    [DbContext(typeof(ContactContext))]
    partial class ContactContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Entities.Models.City", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long>("StateID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.HasIndex("StateID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 1",
                            StateID = 1L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 2",
                            StateID = 1L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 3",
                            StateID = 2L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 4",
                            StateID = 2L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 5",
                            StateID = 3L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 6",
                            StateID = 3L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 7",
                            StateID = 4L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 8",
                            StateID = 4L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 9",
                            StateID = 5L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 10",
                            StateID = 5L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("CityID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("StreetName")
                        .HasColumnType("text");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.HasIndex("CityID");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            CityID = 1L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 1",
                            StreetName = "Street Name",
                            StreetNumber = 2398,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2L,
                            CityID = 2L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 2",
                            StreetName = "Street Name",
                            StreetNumber = 4265,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3L,
                            CityID = 3L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 3",
                            StreetName = "Street Name",
                            StreetNumber = 4405,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4L,
                            CityID = 4L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 4",
                            StreetName = "Street Name",
                            StreetNumber = 2686,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5L,
                            CityID = 5L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 5",
                            StreetName = "Street Name",
                            StreetNumber = 3474,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6L,
                            CityID = 6L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 6",
                            StreetName = "Street Name",
                            StreetNumber = 2348,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7L,
                            CityID = 7L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 7",
                            StreetName = "Street Name",
                            StreetNumber = 2352,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8L,
                            CityID = 8L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 8",
                            StreetName = "Street Name",
                            StreetNumber = 1221,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9L,
                            CityID = 9L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 9",
                            StreetName = "Street Name",
                            StreetNumber = 3538,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10L,
                            CityID = 10L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 10",
                            StreetName = "Street Name",
                            StreetNumber = 738,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Models.Contact", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("CityID")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text");

                    b.Property<string>("StreetName")
                        .HasColumnType("text");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.HasIndex("CityID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            BirthDate = new DateTime(1999, 6, 6, 16, 32, 10, 427, DateTimeKind.Local).AddTicks(4554),
                            CityID = 1L,
                            CompanyID = 1L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail1@mail.com",
                            Name = "Contact 1",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 3346,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2L,
                            BirthDate = new DateTime(1942, 5, 14, 16, 32, 10, 428, DateTimeKind.Local).AddTicks(4744),
                            CityID = 1L,
                            CompanyID = 1L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail2@mail.com",
                            Name = "Contact 2",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 3083,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3L,
                            BirthDate = new DateTime(1993, 5, 31, 16, 32, 10, 428, DateTimeKind.Local).AddTicks(4978),
                            CityID = 2L,
                            CompanyID = 2L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail3@mail.com",
                            Name = "Contact 3",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 4387,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4L,
                            BirthDate = new DateTime(1910, 12, 3, 16, 32, 10, 428, DateTimeKind.Local).AddTicks(5075),
                            CityID = 2L,
                            CompanyID = 2L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail4@mail.com",
                            Name = "Contact 4",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 3459,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5L,
                            BirthDate = new DateTime(1929, 4, 30, 16, 32, 10, 428, DateTimeKind.Local).AddTicks(5167),
                            CityID = 3L,
                            CompanyID = 3L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail5@mail.com",
                            Name = "Contact 5",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 3905,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6L,
                            BirthDate = new DateTime(1981, 3, 19, 16, 32, 10, 428, DateTimeKind.Local).AddTicks(5265),
                            CityID = 3L,
                            CompanyID = 3L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail6@mail.com",
                            Name = "Contact 6",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 2781,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7L,
                            BirthDate = new DateTime(1942, 1, 9, 16, 32, 10, 428, DateTimeKind.Local).AddTicks(5356),
                            CityID = 4L,
                            CompanyID = 4L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail7@mail.com",
                            Name = "Contact 7",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 1066,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8L,
                            BirthDate = new DateTime(1924, 2, 10, 16, 32, 10, 428, DateTimeKind.Local).AddTicks(5446),
                            CityID = 4L,
                            CompanyID = 4L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail8@mail.com",
                            Name = "Contact 8",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 1224,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9L,
                            BirthDate = new DateTime(1937, 5, 11, 16, 32, 10, 428, DateTimeKind.Local).AddTicks(5537),
                            CityID = 5L,
                            CompanyID = 5L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail9@mail.com",
                            Name = "Contact 9",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 4215,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10L,
                            BirthDate = new DateTime(1993, 12, 6, 16, 32, 10, 428, DateTimeKind.Local).AddTicks(5637),
                            CityID = 5L,
                            CompanyID = 5L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail10@mail.com",
                            Name = "Contact 10",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 3427,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 11L,
                            BirthDate = new DateTime(1942, 6, 16, 16, 32, 10, 428, DateTimeKind.Local).AddTicks(5729),
                            CityID = 6L,
                            CompanyID = 6L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail11@mail.com",
                            Name = "Contact 11",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 486,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 12L,
                            BirthDate = new DateTime(1990, 5, 27, 16, 32, 10, 428, DateTimeKind.Local).AddTicks(5821),
                            CityID = 6L,
                            CompanyID = 6L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail12@mail.com",
                            Name = "Contact 12",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 2902,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 13L,
                            BirthDate = new DateTime(1945, 4, 2, 16, 32, 10, 428, DateTimeKind.Local).AddTicks(5913),
                            CityID = 7L,
                            CompanyID = 7L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail13@mail.com",
                            Name = "Contact 13",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 3477,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 14L,
                            BirthDate = new DateTime(1989, 10, 22, 16, 32, 10, 428, DateTimeKind.Local).AddTicks(6004),
                            CityID = 7L,
                            CompanyID = 7L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail14@mail.com",
                            Name = "Contact 14",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 3477,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 15L,
                            BirthDate = new DateTime(1917, 6, 18, 16, 32, 10, 428, DateTimeKind.Local).AddTicks(6252),
                            CityID = 8L,
                            CompanyID = 8L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail15@mail.com",
                            Name = "Contact 15",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 3920,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 16L,
                            BirthDate = new DateTime(1924, 10, 21, 16, 32, 10, 428, DateTimeKind.Local).AddTicks(6352),
                            CityID = 8L,
                            CompanyID = 8L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail16@mail.com",
                            Name = "Contact 16",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 657,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 17L,
                            BirthDate = new DateTime(1956, 8, 23, 16, 32, 10, 428, DateTimeKind.Local).AddTicks(6447),
                            CityID = 9L,
                            CompanyID = 9L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail17@mail.com",
                            Name = "Contact 17",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 453,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 18L,
                            BirthDate = new DateTime(1915, 7, 23, 16, 32, 10, 428, DateTimeKind.Local).AddTicks(6542),
                            CityID = 9L,
                            CompanyID = 9L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail18@mail.com",
                            Name = "Contact 18",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 565,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 19L,
                            BirthDate = new DateTime(1960, 9, 1, 16, 32, 10, 428, DateTimeKind.Local).AddTicks(6635),
                            CityID = 10L,
                            CompanyID = 10L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail19@mail.com",
                            Name = "Contact 19",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 3481,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 20L,
                            BirthDate = new DateTime(1973, 7, 12, 16, 32, 10, 428, DateTimeKind.Local).AddTicks(6729),
                            CityID = 10L,
                            CompanyID = 10L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail20@mail.com",
                            Name = "Contact 20",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 4354,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Models.Phone", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<long>("ContactID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<long>("PhoneTypeID")
                        .HasColumnType("bigint");

                    b.Property<string>("Prefix")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.HasIndex("ContactID");

                    b.HasIndex("PhoneTypeID");

                    b.ToTable("Phones");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            ContactID = 1L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "57971562",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2L,
                            ContactID = 2L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "36946716",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3L,
                            ContactID = 3L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "14971823",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4L,
                            ContactID = 4L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "79254735",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5L,
                            ContactID = 5L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "59650556",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6L,
                            ContactID = 6L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "30230729",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7L,
                            ContactID = 7L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "68007467",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8L,
                            ContactID = 8L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "29560344",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9L,
                            ContactID = 9L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "37111279",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10L,
                            ContactID = 10L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "85289847",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 11L,
                            ContactID = 11L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "66788199",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 12L,
                            ContactID = 12L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "77626861",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 13L,
                            ContactID = 13L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "60773601",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 14L,
                            ContactID = 14L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "62298008",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 15L,
                            ContactID = 15L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "15591661",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 16L,
                            ContactID = 16L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "11142156",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 17L,
                            ContactID = 17L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "55024688",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 18L,
                            ContactID = 18L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "50939302",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 19L,
                            ContactID = 19L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "97733669",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 20L,
                            ContactID = 20L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "32236085",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 21L,
                            ContactID = 1L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "50374484",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 22L,
                            ContactID = 2L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "57065761",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 23L,
                            ContactID = 3L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "30139612",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 24L,
                            ContactID = 4L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "86784561",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 25L,
                            ContactID = 5L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "71070089",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 26L,
                            ContactID = 6L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "73612778",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 27L,
                            ContactID = 7L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "26573683",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 28L,
                            ContactID = 8L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "72639275",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 29L,
                            ContactID = 9L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "60941976",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 30L,
                            ContactID = 10L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "37335700",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 31L,
                            ContactID = 11L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "25711760",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 32L,
                            ContactID = 12L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "43486955",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 33L,
                            ContactID = 13L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "86777028",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 34L,
                            ContactID = 14L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "41403956",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 35L,
                            ContactID = 15L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "64854477",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 36L,
                            ContactID = 16L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "82795824",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 37L,
                            ContactID = 17L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "66712381",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 38L,
                            ContactID = 18L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "83446253",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 39L,
                            ContactID = 19L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "66449358",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 40L,
                            ContactID = 20L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "53803797",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Models.PhoneType", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.ToTable("PhoneTypes");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "work",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "personal",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Models.State", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "State 1",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "State 2",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "State 3",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "State 4",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5L,
                            CreatedAt = new DateTime(2020, 3, 31, 16, 32, 10, 411, DateTimeKind.Local).AddTicks(877),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "State 5",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Models.City", b =>
                {
                    b.HasOne("Entities.Models.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.HasOne("Entities.Models.City", "City")
                        .WithMany("Companies")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Contact", b =>
                {
                    b.HasOne("Entities.Models.City", "City")
                        .WithMany("Contacts")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Phone", b =>
                {
                    b.HasOne("Entities.Models.Contact", "Contact")
                        .WithMany("Phones")
                        .HasForeignKey("ContactID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.PhoneType", "PhoneType")
                        .WithMany("Phones")
                        .HasForeignKey("PhoneTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
