// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Repository;

namespace Repository.Migrations
{
    [DbContext(typeof(ContactContext))]
    partial class ContactContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Entities.Models.City", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<long>("StateID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.HasIndex("StateID");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 1",
                            StateID = 1L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 2",
                            StateID = 1L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 3",
                            StateID = 2L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 4",
                            StateID = 2L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 5",
                            StateID = 3L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 6",
                            StateID = 3L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 7",
                            StateID = 4L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 8",
                            StateID = 4L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 9",
                            StateID = 5L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "City 10",
                            StateID = 5L,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("CityID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("StreetName")
                        .HasColumnType("text");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.HasIndex("CityID");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            CityID = 1L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 1",
                            StreetName = "Street Name",
                            StreetNumber = 656,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2L,
                            CityID = 2L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 2",
                            StreetName = "Street Name",
                            StreetNumber = 2420,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3L,
                            CityID = 3L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 3",
                            StreetName = "Street Name",
                            StreetNumber = 174,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4L,
                            CityID = 4L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 4",
                            StreetName = "Street Name",
                            StreetNumber = 918,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5L,
                            CityID = 5L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 5",
                            StreetName = "Street Name",
                            StreetNumber = 1015,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6L,
                            CityID = 6L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 6",
                            StreetName = "Street Name",
                            StreetNumber = 2273,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7L,
                            CityID = 7L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 7",
                            StreetName = "Street Name",
                            StreetNumber = 3656,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8L,
                            CityID = 8L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 8",
                            StreetName = "Street Name",
                            StreetNumber = 1765,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9L,
                            CityID = 9L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 9",
                            StreetName = "Street Name",
                            StreetNumber = 2762,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10L,
                            CityID = 10L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Company 10",
                            StreetName = "Street Name",
                            StreetNumber = 1861,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Models.Contact", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<long>("CityID")
                        .HasColumnType("bigint");

                    b.Property<long>("CompanyID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text");

                    b.Property<string>("StreetName")
                        .HasColumnType("text");

                    b.Property<int>("StreetNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.HasIndex("CityID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            BirthDate = new DateTime(1992, 12, 16, 12, 42, 54, 278, DateTimeKind.Local).AddTicks(9036),
                            CityID = 1L,
                            CompanyID = 1L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail1@mail.com",
                            Name = "Contact 1",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 2317,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2L,
                            BirthDate = new DateTime(1931, 2, 20, 12, 42, 54, 279, DateTimeKind.Local).AddTicks(1289),
                            CityID = 1L,
                            CompanyID = 1L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail2@mail.com",
                            Name = "Contact 2",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 1453,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3L,
                            BirthDate = new DateTime(1914, 9, 3, 12, 42, 54, 279, DateTimeKind.Local).AddTicks(1393),
                            CityID = 2L,
                            CompanyID = 2L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail3@mail.com",
                            Name = "Contact 3",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 1211,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4L,
                            BirthDate = new DateTime(1927, 11, 7, 12, 42, 54, 279, DateTimeKind.Local).AddTicks(1429),
                            CityID = 2L,
                            CompanyID = 2L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail4@mail.com",
                            Name = "Contact 4",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 2465,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5L,
                            BirthDate = new DateTime(1925, 6, 30, 12, 42, 54, 279, DateTimeKind.Local).AddTicks(1458),
                            CityID = 3L,
                            CompanyID = 3L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail5@mail.com",
                            Name = "Contact 5",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 287,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6L,
                            BirthDate = new DateTime(1948, 12, 21, 12, 42, 54, 279, DateTimeKind.Local).AddTicks(1490),
                            CityID = 3L,
                            CompanyID = 3L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail6@mail.com",
                            Name = "Contact 6",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 3698,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7L,
                            BirthDate = new DateTime(1956, 7, 13, 12, 42, 54, 279, DateTimeKind.Local).AddTicks(1518),
                            CityID = 4L,
                            CompanyID = 4L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail7@mail.com",
                            Name = "Contact 7",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 298,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8L,
                            BirthDate = new DateTime(1932, 3, 27, 12, 42, 54, 279, DateTimeKind.Local).AddTicks(1545),
                            CityID = 4L,
                            CompanyID = 4L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail8@mail.com",
                            Name = "Contact 8",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 3549,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9L,
                            BirthDate = new DateTime(1999, 2, 17, 12, 42, 54, 279, DateTimeKind.Local).AddTicks(1572),
                            CityID = 5L,
                            CompanyID = 5L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail9@mail.com",
                            Name = "Contact 9",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 4815,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10L,
                            BirthDate = new DateTime(1960, 5, 13, 12, 42, 54, 279, DateTimeKind.Local).AddTicks(1656),
                            CityID = 5L,
                            CompanyID = 5L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail10@mail.com",
                            Name = "Contact 10",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 2127,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 11L,
                            BirthDate = new DateTime(1940, 6, 27, 12, 42, 54, 279, DateTimeKind.Local).AddTicks(1687),
                            CityID = 6L,
                            CompanyID = 6L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail11@mail.com",
                            Name = "Contact 11",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 4071,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 12L,
                            BirthDate = new DateTime(1933, 5, 13, 12, 42, 54, 279, DateTimeKind.Local).AddTicks(1715),
                            CityID = 6L,
                            CompanyID = 6L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail12@mail.com",
                            Name = "Contact 12",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 228,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 13L,
                            BirthDate = new DateTime(1923, 3, 3, 12, 42, 54, 279, DateTimeKind.Local).AddTicks(1742),
                            CityID = 7L,
                            CompanyID = 7L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail13@mail.com",
                            Name = "Contact 13",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 697,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 14L,
                            BirthDate = new DateTime(1925, 4, 25, 12, 42, 54, 279, DateTimeKind.Local).AddTicks(1769),
                            CityID = 7L,
                            CompanyID = 7L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail14@mail.com",
                            Name = "Contact 14",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 4904,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 15L,
                            BirthDate = new DateTime(2000, 1, 14, 12, 42, 54, 279, DateTimeKind.Local).AddTicks(1796),
                            CityID = 8L,
                            CompanyID = 8L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail15@mail.com",
                            Name = "Contact 15",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 1797,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 16L,
                            BirthDate = new DateTime(1972, 2, 13, 12, 42, 54, 279, DateTimeKind.Local).AddTicks(1823),
                            CityID = 8L,
                            CompanyID = 8L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail16@mail.com",
                            Name = "Contact 16",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 2357,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 17L,
                            BirthDate = new DateTime(1965, 4, 8, 12, 42, 54, 279, DateTimeKind.Local).AddTicks(1850),
                            CityID = 9L,
                            CompanyID = 9L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail17@mail.com",
                            Name = "Contact 17",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 1626,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 18L,
                            BirthDate = new DateTime(1940, 2, 18, 12, 42, 54, 279, DateTimeKind.Local).AddTicks(1879),
                            CityID = 9L,
                            CompanyID = 9L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail18@mail.com",
                            Name = "Contact 18",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 1413,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 19L,
                            BirthDate = new DateTime(1982, 6, 21, 12, 42, 54, 279, DateTimeKind.Local).AddTicks(1906),
                            CityID = 10L,
                            CompanyID = 10L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail19@mail.com",
                            Name = "Contact 19",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 657,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 20L,
                            BirthDate = new DateTime(1936, 12, 24, 12, 42, 54, 279, DateTimeKind.Local).AddTicks(1932),
                            CityID = 10L,
                            CompanyID = 10L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ContactEmail20@mail.com",
                            Name = "Contact 20",
                            ProfileImage = "ImageUrl",
                            StreetName = "Street Name",
                            StreetNumber = 125,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Models.Phone", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<long>("ContactID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Number")
                        .HasColumnType("text");

                    b.Property<long>("PhoneTypeID")
                        .HasColumnType("bigint");

                    b.Property<string>("Prefix")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.HasIndex("ContactID");

                    b.HasIndex("PhoneTypeID");

                    b.ToTable("Phones");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            ContactID = 1L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "13734999",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2L,
                            ContactID = 2L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "79097884",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3L,
                            ContactID = 3L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "96494823",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4L,
                            ContactID = 4L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "56596996",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5L,
                            ContactID = 5L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "20905987",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 6L,
                            ContactID = 6L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "58248277",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 7L,
                            ContactID = 7L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "48832024",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 8L,
                            ContactID = 8L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "56680530",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 9L,
                            ContactID = 9L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "53217546",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 10L,
                            ContactID = 10L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "49100529",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 11L,
                            ContactID = 11L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "54790487",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 12L,
                            ContactID = 12L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "69226462",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 13L,
                            ContactID = 13L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "93573875",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 14L,
                            ContactID = 14L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "17369239",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 15L,
                            ContactID = 15L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "60698586",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 16L,
                            ContactID = 16L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "79901067",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 17L,
                            ContactID = 17L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "19684141",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 18L,
                            ContactID = 18L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "57936918",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 19L,
                            ContactID = 19L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "68676005",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 20L,
                            ContactID = 20L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "44173582",
                            PhoneTypeID = 1L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 21L,
                            ContactID = 1L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "98047322",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 22L,
                            ContactID = 2L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "68472666",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 23L,
                            ContactID = 3L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "52178564",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 24L,
                            ContactID = 4L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "99050265",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 25L,
                            ContactID = 5L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "44409188",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 26L,
                            ContactID = 6L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "44905766",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 27L,
                            ContactID = 7L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "35613259",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 28L,
                            ContactID = 8L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "66995080",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 29L,
                            ContactID = 9L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "32389566",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 30L,
                            ContactID = 10L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "12598548",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 31L,
                            ContactID = 11L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "68385440",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 32L,
                            ContactID = 12L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "74386497",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 33L,
                            ContactID = 13L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "15776042",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 34L,
                            ContactID = 14L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "73264909",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 35L,
                            ContactID = 15L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "51334055",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 36L,
                            ContactID = 16L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "15499190",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 37L,
                            ContactID = 17L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "75899170",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 38L,
                            ContactID = 18L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "58551422",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 39L,
                            ContactID = 19L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "69207382",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 40L,
                            ContactID = 20L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Number = "65255083",
                            PhoneTypeID = 2L,
                            Prefix = "549",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Models.PhoneType", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.ToTable("PhoneTypes");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "work",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "personal",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Models.State", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("DeletedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("ID");

                    b.ToTable("States");

                    b.HasData(
                        new
                        {
                            ID = 1L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "State 1",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 2L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "State 2",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 3L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "State 3",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 4L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "State 4",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            ID = 5L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 42, 54, 274, DateTimeKind.Local).AddTicks(5067),
                            DeletedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "State 5",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Entities.Models.City", b =>
                {
                    b.HasOne("Entities.Models.State", "State")
                        .WithMany("Cities")
                        .HasForeignKey("StateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Company", b =>
                {
                    b.HasOne("Entities.Models.City", "City")
                        .WithMany("Companies")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Contact", b =>
                {
                    b.HasOne("Entities.Models.City", "City")
                        .WithMany("Contacts")
                        .HasForeignKey("CityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.Phone", b =>
                {
                    b.HasOne("Entities.Models.Contact", "Contact")
                        .WithMany("Phones")
                        .HasForeignKey("ContactID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.PhoneType", "PhoneType")
                        .WithMany("Phones")
                        .HasForeignKey("PhoneTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
